name: Convert image
on: [workflow_dispatch]

jobs:
  convert-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tools
        run: sudo bash tools/install-tools.sh
      - name: Convert images
        run: |
          sudo -E bash tools/start-containerd.sh
          sudo -E python -u ./convert_images.py
